version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: run tests
          command: |
            npm run unit-tests
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./
 sast:
    docker:
      - images: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install NodeJsScan
          command:
              sudo apt update
              sudo apt install python3-pip
              pip3 install nodejsscan
      - run:
          name: Run NodeJsScan
          command: |
            nodejsscan -d ./
      - run:
           name: Run NodeJsScan
           command: |
            nodejsscan -d ./ -o sast-output.json
      - store artefacts:
          path: sast-output.json
      - run:
          name: Parse sast report
          command: |
            # exit with a non-zero exit code if there are any security issues
            exit $(cat sast-output.json) | jq .total_count.sec)


workflows:
  build-and-packge:
    jobs:
      - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master
            
workflows:
    build-and-package:
        jobs:
            - ci-build
            - integration-tests:
                requires:
                    - ci-build
            - sast:
                requires:
                    - ci-build